version: "3"
services:
  product-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-container
    image: product-management-api
    restart: always
    ports:
      - "7610:7610"
    tty: true
    container_name: product-management-api
    env_file:
      - .env
    networks:
      - shared_net

networks:
  shared_net:
    external: true
