name: Deploy to main Server

on:
  push:
    branches: main

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy files to SSH Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: /home/alvian/app/product-management-api/

      - name: SSH into server instance and start app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/alvian/app/product-management-api/
            echo "${{ secrets.ENV_FILE }}" > .env
            docker compose -f docker-compose.yml down --rmi all
            docker compose -f docker-compose.yml build --no-cache
            docker compose -f docker-compose.yml up -d --force-recreate
            docker system prune -f
